# 파일 복사후 런서버 실행
FROM            eb-docker:base
MAINTAINER      dosio0102@gmail.ccm

ENV             BUILD_MODE      local
ENV             DJANGO_SETTINGS_MODULE  config.settings.${BUILD_MODE}

WORKDIR         /srv/project/app
COPY            .   /srv/project
