FROM            python:3.6.5-slim
MAINTAINER      dosio0102@gmail.ccm

RUN             apt -y update && apt -y dist-upgrade
RUN             apt -y install build-essential
RUN             apt -y install nginx supervisor


#도커 안에서 구지 pipenv를 설치하고 사용하지 않으려고 requirements를 사용
COPY            ./requirements.txt   /srv/
RUN             pip install -r /srv/requirements.txt

