# 파일 복사후 런서버 실행
FROM            eb-docker:base
MAINTAINER      dosio0102@gmail.com

ENV             BUILD_MODE      dev
ENV             DJANGO_SETTINGS_MODULE  config.settings.${BUILD_MODE}

COPY            ./requirements.txt  /srv/
RUN             pip install -r /srv/requirements.txt

COPY            .   /srv/project

RUN             cp -f   /srv/project/.config/${BUILD_MODE}/nginx.conf \
                        /etc/nginx/nginx.conf && \
                cp -f   /srv/project/.config/${BUILD_MODE}/nginx_app.conf \
                        /etc/nginx/sites-available/ && \
                rm -f   /etc/nginx/sites-enabled/* && \
                ln -s   /etc/nginx/sites-available/nginx_app.conf \
                        /etc/nginx/sites-enabled/

RUN             cp -f   /srv/project/.config/${BUILD_MODE}/supervisor.conf \
                        /etc/supervisor/conf.d/

CMD             supervisord -n